### PR TITLE
Initialized  test projects

### PR DESCRIPTION
**Pull request by coeur85**
create acceptance and unit tests

### CODE REVIEW

**Comment by ElbekDeveloper** [comment]
> create acceptance and unit tests
https://github.com/hassanhabib/Refugee.Core/pull/18 brother, please look at how he implemented the issue. I have left my comments in this PR as well. https://www.youtube.com/watch?v=9i4dTI_5bM0&list=PLan3SCnsISTQ63o4HFkIw0YcEcOlwqt53&index=2 this video can be reference

**Comment by Spectralgo** [comment]
> create acceptance and unit tests

Do you wanna do a code session with me?

**Comment by coeur85** [comment]
> > create acceptance and unit tests
> 
> Do you wanna do a code session with me? @coeur85 

That's fine with me, what time r u available?

**Comment by Spectralgo** [comment]
> > > create acceptance and unit tests
> > 
> > Do you wanna do a code session with me? @coeur85 
> 
> That's fine with me, what time r u available?

Let's talk about it on discord

**Pull request closed without merging**
