### PR TITLE
BROKERS: Add Host Broker - Insert/Select all/Select by Id/Update/Delete

### PR DESCRIPTION
**Pull request by Spectralgo**

### CODE REVIEW

**Comment by ElbekDeveloper** [comment]
nope @Spectralgo, you can't cut corners like this. You add one method, finish the feature end-to-end and move to the next one. Or, separate each commit to its own PR. You can do the `cherry pick` for this.

**Comment by Spectralgo** [comment]
@ElbekDeveloper I understand the splitting into several PRs and I'll do it. But I don't understand the first choice you gave me.

**Comment by ElbekDeveloper** [comment]
1. BROKERS: Insert Shelter
2. FOUNDATIONS: Add Shelter
3. EXPOSERS: Post Shelter
4. BROKERS: Retrieve All Shelters 
5. ...

**Comment by Spectralgo** [comment]
All the features are separated into different commits. The commit history will be clean in the main branch

**Comment by ElbekDeveloper** [comment]
> All the features are separated into different commits. The commit history will be clean in the main branch

Yes, I saw and I liked it.  Unfortunately, all these are too much for one PR. Sorry, for being so strict

**Comment by Spectralgo** [comment]
@ElbekDeveloper ok I see. No grouping of vertical slice/integration into PRs

**Pull request closed without merging**
